---
# Ansible playbook for Fedora Workstation setup
#
# Usage: ./run-playbook.sh
# Usage (specific roles): ./run-playbook.sh --tags base,multimedia
# Usage (specific host): ./run-playbook.sh -l hostname

- name: Configure Fedora Workstation
  hosts: all
  gather_facts: true

  # group_vars/all/main.yml and host_vars/ auto-loaded by Ansible
  # vault.yml loaded by roles that need it (networking, resticprofile)

  roles:
    - role: networking
      tags: [networking, tailscale]
    - role: base
      tags: [base, repos]
    - role: onepassword
      tags: [onepassword, desktop]
    - role: notebook
      tags: [notebook, power]
    - role: desktop
      tags: [desktop, gui]
    - role: multimedia
      tags: [multimedia, codecs]
    - role: hyprland
      tags: [hyprland, wayland]
    - role: niri
      tags: [niri, wayland]
    - role: vicinae
      tags: [desktop, vicinae]
    - role: ghostty
      tags: [desktop, ghostty]
    - role: beyondcompare
      tags: [desktop, beyondcompare]
    - role: vscode
      tags: [desktop, vscode]
    - role: zfs
      tags: [zfs, zrepl, storage]
    - role: btrbk
      tags: [btrbk, storage, backup]
    - role: resticprofile
      tags: [resticprofile, backup]
    - role: smartcard
      tags: [smartcard, gpg]
    - role: virtualization
      tags: [virtualization, incus, docker, containers]
# vim: set ft=yaml.ansible:
